const starterPacks = {
    "Cleric": [
        "cudgel, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, wooden cross, 4 GP",
        "cudgel, shield, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, wooden cross, 4 GP",
        "mace, leather armor, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, wooden cross, 5 GP",
        "quarter-staff, leather armor, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, 12 iron spikes, wooden cross, 3 stakes & mallet, steel mirror, 10 GP",
        "chain armor, war hammer, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, wooden cross, 2 small sacks, 8 GP",
        "chain armor, shield, mace, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, wooden cross, 2 small sacks, 8 GP",
        "chain armor, shield, war hammer, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, wooden cross, 2 small sacks, 3 stakes & mallet, steel mirror, 10 GP",
        "plate armor, shield, mace, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, wooden cross, 10 GP",
        "plate armor, shield, war hammer, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 10' pole, wooden cross, small sack, 2 GP",
        "plate armor, quarter-staff, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 50' rope, silver cross, 4 GP",
        "cudgel, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, wooden cross, scroll, 4 GP",
        "plate armor, shield, mace, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 50' rope, silver cross, 10 GP",
        "leather armor, mace, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, wooden cross, scroll, 2 flasks oil, 1 GP",
        "plate armor, shield, helmet, war hammer, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 50' rope, silver cross, 3 stakes & mallet, steel mirror, 12 GP",
        "chain armor, war hammer, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, wooden cross, scroll, 10 GP",
        "plate armor, shield, helmet, mace, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 50' rope, silver cross, vial holy water, 12 iron spikes, 3 stakes & mallet, small sack, 10 GP"
    ],
    "Fighter": [
        "spear, dagger, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, 3 GP",
        "cudgel, leather armor, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, 1 GP",
        "leather armor, morning star, dagger, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, 3 GP",
        "leather armor, battle axe, hand axe, dagger, sling, pouch with 20 sling bullets, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, 7 GP",
        "chain armor, spear, dagger, sling, pouch with 20 sling bullets, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, 11 GP",
        "chain armor, shield, sword, dagger, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, 4 GP",
        "chain armor, spear, light crossbow, case with 30 quarrels, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, 11 GP",
        "plate armor, shield, sword, dagger, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, 4 GP",
        "plate armor, two-handed sword, 3 daggers, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, 2 flasks oil, 9 GP",
        "plate armor, shield, sword, light crossbow, case with 30 quarrels, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, 2 GP",
        "plate armor, flail, dagger, 35 short bow, quiver of 20 arrows, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, small sack, 10 GP",
        "plate armor, shield, sword, light crossbow, case with 30 quarrels, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 10' pole, 5 GP",
        "plate armor, helmet, 2 battle axes, dagger, light crossbow, case with 30 quarrels, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, 5 flasks oil, 15 GP",
        "plate armor, two-handed sword, dagger, short bow, quiver of 20 arrows, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 10' pole, 2 small sacks, 15 GP",
        "plate armor, halberd, dagger, long bow, quiver of 20 arrows, 2 silver tipped arrows, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 50' rope, 10 GP",
        "plate armor, shield, helmet, sword, 2 daggers, light crossbow, case with 30 quarrels, 4 silver tipped quarrels, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 10' pole, 9 GP"
    ],
    "Magic User": [
        "dagger, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole, 4 GP",
        "2 daggers, 6 torches, backpack, waterskin, 1 week iron rations, 2 flasks oil, 50' rope, 7 GP",
        "dagger, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 10' pole, 7 GP",
        "dagger, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, vial of holy water, 9 GP",
        "dagger, 6 torches, backpack, waterskin, 1 week iron rations, 10' pole 5 flasks of oil, silver mirror, belladona, 9 GP",
        "dagger, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, 2 vials holy water, 4 GP",
        "3 daggers, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 10' pole, vial of holy water, 16 GP",
        "dagger, 6 torches, backpack, waterskin, 1 week iron rations, 50' rope, 2 vials holy water, 24 GP",
        "dagger, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 10' pole, 67 GP",
        "dagger, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, 50' rope, 77 GP",
        "dagger, 6 torches, backpack, waterskin, 1 week iron rations, scroll, 10' pole, 4 GP",
        "2 daggers, 6 torches, backpack, waterskin, 1 week iron rations, scroll, 50' rope, 11 GP",
        "dagger, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, scroll, 10' pole, 7 GP",
        "dagger, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, scroll, 50' rope, 17 GP",
        "dagger, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, scroll, 10' pole, 27 GP",
        "dagger, backpack, waterskin, lantern, 4 flasks oil, 1 week iron rations, scroll, 50' rope, 37 GP"
    ]
};
