
const terrains = ["Barren", "Coast", "Forest", "Hills", "Jungle", "Mountains", "Open", "River", "Settled", "Swamp"];

const arrayEncounterLevelByDungeonLevel = {
    dungeon_level: {
        1: {roll: {1: {lv: 1}, 2: {lv: 1}, 3: {lv: 1}, 4: {lv: 2}, 5: {lv: 2}, 6: {lv: 3}}},
        2: {roll: {1: {lv: 1}, 2: {lv: 2}, 3: {lv: 2}, 4: {lv: 2}, 5: {lv: 3}, 6: {lv: 3}}},
        3: {roll: {1: {lv: 2}, 2: {lv: 3}, 3: {lv: 3}, 4: {lv: 3}, 5: {lv: 4}, 6: {lv: 4}}},
        4: {roll: {1: {lv: 3}, 2: {lv: 4}, 3: {lv: 4}, 4: {lv: 4}, 5: {lv: 5}, 6: {lv: 5}}},
        5: {roll: {1: {lv: 4}, 2: {lv: 5}, 3: {lv: 5}, 4: {lv: 5}, 5: {lv: 6}, 6: {lv: 6}}},
        6: {roll: {1: {lv: 5}, 2: {lv: 6}, 3: {lv: 6}, 4: {lv: 6}, 5: {lv: 7}, 6: {lv: 8}}},
        7: {roll: {1: {lv: 6}, 2: {lv: 7}, 3: {lv: 7}, 4: {lv: 7}, 5: {lv: 8}, 6: {lv: 9}}},
        8: {roll: {1: {lv: 7}, 2: {lv: 7}, 3: {lv: 8}, 4: {lv: 8}, 5: {lv: 8}, 6: {lv: 9}}},
        9: {roll: {1: {lv: 8}, 2: {lv: 8}, 3: {lv: 9}, 4: {lv: 9}, 5: {lv: 9}, 6: {lv: 10}}},
        10: {roll: {1: {lv: 8}, 2: {lv: 9}, 3: {lv: 9}, 4: {lv: 10}, 5: {lv: 10}, 6: {lv: 10}}}
    }
};

// Template
/*
{
    name: "",
    form: "",
    hit_dice: number,
    hit_dice_mod: number,
    HDE: number,
    toHitBonus: number,
    armor_class_descend: number,
    armor_class_ascend: number,
    attack: "",
    special: "",
    move: number,
    XP: number,
    saving_throw: number,
    dungeon_levels: [],
    terrain: [""],
    notes: ""
},
*/


const arrayMonsters = [
    {
        name: "Banshee",
        form: "Undead",
        hit_dice: 7,
        hit_dice_mod: 0,
        HDE: 11,
        toHitBonus: 7,
        armor_class_descend: 0,
        armor_class_ascend: 19,
        attack: "Claw",
        special: "See notes",
        move: 12,
        XP: 1700,
        saving_throw: 12,
        dungeon_levels: [7],
        terrain: ["Settled", "Swamp", "Jungle", "Barren"],
        notes: "Banshees are horrid fey (or undead) creatures that live in swamps and other desolate places. They can only be harmed by magical or silver weapons. Banshees have a 49% resistance to magic, and they are immune to enchantments. Their shriek (once per day) necessitates a saving throw versus death or the hearer will die in 2d6 rounds. They can travel over water and other terrain as if it were land, but crossing running water causes it to lose its magic resistance for 3d6 hours. They look like gaunt humans with long, stringy hair and glowing yellow eyes. They often wear hooded cloaks. At the Referee's discretion, such creatures might be undead rather than faerie-folk, and are considered to have 9 HD for turning purposes."
    },
    {
        name: "Basilisk",
        form: "Monster",
        hit_dice: 6,
        hit_dice_mod: 0,
        HDE: 8,
        toHitBonus: 6,
        armor_class_descend: 4,
        armor_class_ascend: 15,
        attack: "Bite",
        special: "Petrifying Gaze",
        move: 6,
        XP: 800,
        saving_throw: 13,
        dungeon_levels: [6],
        terrain: ["Barren", "Hills", "Mountains", "Open", "Forest", "River", "Coast", "Swamp", "Jungle"],
        notes: "Basilisks are great lizards whose gaze turns to stone anyone meeting its eye (fighting without looking incurs a -4 penalty 'to-hit'). If the basilisk's own gaze is reflected back at it, it has a 10% chance to force the basilisk into a saving throw against being turned to stone itself."
    },
    {
        name: "Beetle, Giant Fire",
        form: "Animal",
        hit_dice: 1,
        hit_dice_mod: 3,
        HDE: 1,
        toHitBonus: 1,
        armor_class_descend: 4,
        armor_class_ascend: 15,
        attack: "Bite",
        special: "None",
        move: 12,
        XP: 15,
        saving_throw: 18,
        dungeon_levels: [1, 2],
        terrain: ["Coast", "River", "Open", "Forest", "Swamp", "Jungle"],
        notes: "A giant fire beetle's oily light-glands glow red, and continue to give off light for 1d6 days after they are removed (shedding light in a 10 foot radius)."
    },
    {
        name: "Black Pudding",
        form: "Unknown",
        hit_dice: 10,
        hit_dice_mod: 0,
        HDE: 11,
        toHitBonus: 0,
        armor_class_descend: 6,
        armor_class_ascend: 13,
        attack: "Strike",
        special: "Acidic",
        move: 6,
        XP: 1700,
        saving_throw: 9,
        dungeon_levels: [10],
        terrain: ["Barren", "Coast", "Forest", "Hills", "Jungle", "Mountains", "Open", "River", "Settled", "Swamp"],
        notes: "Black puddings are amorphous globs with an acidic surface. They are subterranean predators and scavengers. Any weapon or armor contacting a black pudding will be eaten away by the acid as follows: weapon (1 hit by weapon on the pudding), chain mail or lesser armor (1 hit by pudding), plate mail (2 hits by pudding). If a weapon or armor is magical, it can take an additional hit per +1 before being dissolved. They are immune to cold and divide when attacked by lightning."
    },
    {
        name: "Blink Dog",
        form: "Monster",
        hit_dice: 6,
        hit_dice_mod: 0,
        HDE: 4,
        toHitBonus: 6,
        armor_class_descend: 5,
        armor_class_ascend: 14,
        attack: "Bite",
        special: "Teleport",
        move: 12,
        XP: 120,
        saving_throw: 13,
        dungeon_levels: [6],
        terrain: ["Open", "Forest"],
        notes: "Blink dogs are pack hunters, intelligent and usually friendly to those who are not of evil intent. They can teleport short distances (without error) and attack in the same turn—in most cases (75%) a blink dog will be able to teleport behind an opponent and attack from the rear (with bonuses)."
    },
    {
        name: "Bugbear",
        form: "Humanoid",
        hit_dice: 3,
        hit_dice_mod: 1,
        HDE: 3,
        toHitBonus: 3,
        armor_class_descend: 5,
        armor_class_ascend: 14,
        attack: "Weapon or Bite",
        special: "Surprise opponents",
        move: 9,
        XP: 60,
        saving_throw: 16,
        dungeon_levels: [3],
        terrain: ["Swamp", "Jungle", "Open", "Forest"],
        notes: "These large, hairy, goblin-like humanoids are stealthier than their size would suggest, almost always getting the chance to surprise even the most alert opponents with a roll of 1-3 on a d6 (50% of the time)."
    },
    {
        name: "Centaur",
        form: "Monster",
        hit_dice: 4,
        hit_dice_mod: 0,
        HDE: 5,
        toHitBonus: 4,
        armor_class_descend: 5,
        armor_class_ascend: 14,
        attack: "Weapon or Kick",
        special: "None",
        move: 18,
        XP: 240,
        saving_throw: 15,
        dungeon_levels: [0],
        terrain: ["Open", "Forest"],
        notes: "Half man, half horse, centaurs are fierce warriors and well-known creatures of mythology. The Referee may choose any “version” of the centaur from folklore for his campaign: some are chaotic, some aloof, and some are soothsayers."
    },
    {
        name: "Kobold",
        form: "Humanoid",
        hit_dice: 0,
        hit_dice_mod: 0,
        HDE: 0,
        toHitBonus: 0,
        armor_class_descend: 6,
        armor_class_ascend: 13,
        attack: "Weapon",
        special: "None",
        move: 6,
        XP: 10,
        saving_throw: "19 - HD",
        dungeon_levels: [1],
        terrain: ["Settled", "Hills", "Mountains", "Barren", "Swamp", "Jungle", "Open", "Forest"],
        notes: "Kobolds are subterranean, vaguely goblin-like humanoids. They have a -1 “to-hit” penalty when fighting above ground. Many use slings or short bows, and they fight with short swords or spiked clubs in melee combat."
    }
];